project_id = "CRMCHURCH"

[api]
enabled = true
port = 55121
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55130
shadow_port = 55120
major_version = 15

[db.pooler]
enabled = false
port = 55129
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[realtime]
enabled = true

[studio]
enabled = true
port = 55123
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 55124

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["http://127.0.0.1:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
enable_signup = true
enable_anonymous_sign_ins = false
minimum_password_length = 6
password_requirements = ""

[auth.email]
enable_signup = true
enable_confirmations = false
double_confirm_changes = false
secure_password_change = false
otp_length = 6
otp_expiry = 3600

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"
max_frequency = "5s"

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 58183
deno_version = 2

[analytics]
enabled = true
port = 55127
backend = "postgres"
